---
sudo: required

language: python

python: "3.8"

services:
  - docker

addons:
  apt:
    packages:
      - python-pip

install:
  - pip install ansible molecule[docker,lint]

script:
  - molecule test
# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/
