---
- name: Add Docker GPG apt key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  retries: 3
  delay: 30
  register: result
  until: result is succeeded

- name: Add Docker Repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_facts['lsb']['codename'] }} stable
    state: present
    update_cache: true
  retries: 3
  delay: 30
  register: result
  until: result is succeeded

- name: Create /etc/docker directory
  become: true
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: "0755"

- name: Make docker use systemd to manage cgroups
  become: true
  ansible.builtin.copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
    mode: "0755"

- name: Update apt and Install docker-ce
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 3600
    state: present
  retries: 3
  delay: 10
  register: result
  until: result is succeeded
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Add remote "{{ ansible_user }}" user to "docker" group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Apply chmod on docker.sock
  become: true
  ansible.builtin.file:
    path: /var/run/docker.sock
    mode: a+x
  notify: Restart Docker
