---
- name: Verify
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Initialize role without actually running it
      include_role:
        name: my_role
        tasks_from: init
