name: Molecule

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"

      - name: Molecule
        uses: monolithprojects/action-molecule@v1.4.1
        with:
          molecule_command: test
          scenario: ${{ matrix.scenario }}
