name: Molecule

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: molecule
        uses: robertdebock/molecule-action@4.0.8
        with:
          command: lint

  test:
    runs-on: ubuntu-20.04
    needs:
      - lint
    steps:
      - uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"

      - name: molecule
        uses: robertdebock/molecule-action@4.0.8
        with:
          image: "ubuntu"
          options: parallel
          scenario: default
